services:
  db:
    image: postgres:16
    container_name: grocery_db
    environment:
      POSTGRES_DB: grocery
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - grocery_data:/var/lib/postgresql/data

volumes:
  grocery_data:

